### ISSUE TITLE
Cannot export an alpha mask

### ISSUE THREAD

**Issue by xCyborg** [AllegorithmicSAS/painter-plugin-photoshop-export#37]
Hello?
Anyone here?
The plugin does not export an alpha mask for the texture sets.
I want to merge the texture sets but can't without and alpha mask.

**Comment by robinfaury** [comment]
Hi,

Thank you for reporting this issue. You can see the fix into the last pull request. We'll merge it as soon as possible.
If you need it now, you can apply the fix into your Allegorithmic's plugins folder. You just need to remove the "exportConfig.keepAlpha = false" line from photoshop.js.
![plugins_folder](https://user-images.githubusercontent.com/4552930/62958346-cf5b9180-bdf6-11e9-9435-804e9891740a.png)


Regards,
robin

**Comment by xCyborg** [comment]
Thanks, that's awesome.
